-- 1. Users & Settings
CREATE TABLE IF NOT EXISTS user_settings (
    user_id BIGINT PRIMARY KEY,
    interest TEXT,
    language TEXT DEFAULT 'en'
);

-- 2. Waiting Queue
CREATE TABLE IF NOT EXISTS waiting_queue (
    user_id BIGINT PRIMARY KEY,
    interest TEXT
);

-- 3. Active Chats
CREATE TABLE IF NOT EXISTS active_chats (
    user_id BIGINT PRIMARY KEY,
    partner_id BIGINT
);

-- 4. Blocked Users
CREATE TABLE IF NOT EXISTS blocked_users (
    user_id BIGINT,
    blocked_user_id BIGINT,
    PRIMARY KEY (user_id, blocked_user_id)
);

-- 5. Reports
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT,
    reported_id BIGINT,
    reason TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Message Logs (Optional, for debugging)
CREATE TABLE IF NOT EXISTS message_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT,
    sender_msg_id BIGINT,
    receiver_id BIGINT,
    receiver_msg_id BIGINT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Enable Row Level Security (Optional but recommended)
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE waiting_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE active_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocked_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_logs ENABLE ROW LEVEL SECURITY;

-- 8. Create Policies (Allow full access for service_role/bot)
-- Note: The bot uses the 'service_role' key which bypasses RLS, so these are strictly for if you use the 'anon' key.
-- For simplicity, we are assuming service_role usage.
